name: CI for Docker
on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        env:
          DEFAULT_BRANCH: main
          run: ./action.yml
